setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

filebeat:
  inputs:
    - type: log
      json.keys_under_root: true
      enabled: true
      stream: all
      paths:
        - /var/log/ipeoplecloud/*.log
